import './globals.css'
import { AppProviders } from '@/context/Providers'
import { Toaster } from 'sonner'

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body>
				<AppProviders>
					{children}
					<Toaster position="bottom-right" />
				</AppProviders>
			</body>
		</html>
	)
}
